### ISSUE TITLE
Compile and install UTF-8 mode object code if YottaDB/GT.M is installed with UTF-8 mode support

### ISSUE THREAD

**Issue by ksbhaskar** [shabiel/M-Web-Server#39]
If a YottaDB/GT.M installation directory includes UTF-8 support, the M-Web-Server make should compiles and install object code compiled in UTF-8 mode as well. It currently only compiles and installs M mode object code.

**Comment by shabiel** [comment]
I don't maintain the CMake code; it's actually upstream YottaDB code. If you fix it there, please make sure to copy the CMake file here.
