### ISSUE TITLE
https server

### ISSUE THREAD

**Issue by mabramowicz** [shabiel/M-Web-Server#46]
Hi!

It is possible to force TLS 1.2 only?

I am using key and certificate, this standard way defined in documentation.

I can connect to server with TLS 1.0, 1.1, but it looks security team force to use 1.2.

Kind regards
michal abramowicz

**Comment by shabiel** [comment]
Michal,

Do you use YottaDB or GTM or Cache?

**Comment by mabramowicz** [comment]
Hi!

It is running on yottadb.



config file: gtmcrypt_config.libconfig

tls: {
 edf: {
  format: "PEM";
  cert: "/u01/edf/cert/mycert.pem";
  key:  "/u01/edf/cert/mycert.key";
 }
}


installed openssl packages:

openssl-libs-1.0.2k-19.0.1.el7.x86_64
openssl-devel-1.0.2k-19.0.1.el7.x86_64
openssl-1.0.2k-19.0.1.el7.x86_64


used package: yottadb_r124_rhel7_x8664_pro.tgz


job is started like that

./dm <<EOF
do JOB^VPRJREQ(8443,"edf")
halt
EOF

Kind regards
Michal Abramowicz

**Comment by shabiel** [comment]
Okay. Take a look here: https://docs.yottadb.com/AdminOpsGuide/tls.html

And since you use this in production, if you have support with YottaDB
LLC, you should contact them with any issues in TLS.

--Sam

**Comment by mabramowicz** [comment]
Thanks for answer. 

So I will go to yottadb ...

Kind regards
Michal
