### ISSUE TITLE
Question: Project status and maturity?

### ISSUE THREAD

**Issue by jensli** [shabiel/M-Web-Server#47]
Hello!

This project is interesting to us for implementing a network interface to a GTM application. The project looks professionally developed, tested and documented.

Before we start relying on this projects we'd like to ask its authors the following questions:

* In your opinion, is this project mature enough to be used in a production environment?
* What is the activity level in the project? Will critical bugs be fixed in a reasonable time? 
 
 Regardless, we appreciate that you have published such a nice looking project and contributed to the GTM ecosystem!

**Comment by shabiel** [comment]
Hello @jensli ,

1. The project is definitely used in 1 production environment, and probably in many other instances I am not aware of.
2. I don't get paid to maintain this right now; with that, I won't promise to fix any bugs. The project is really 3 files of source code. So if you find an issue, make a PR and will accept it.

PS: I work for YottaDB; if you get a support agreement with us, I will fix bugs that come up.

**Comment by jensli** [comment]
Thanks for your response. We will evaluate using this project. I just got it working locally, it was easy. It would be so much nicer to be able to use HTTP than to roll our own protocol.

**Comment by jensli** [comment]
(I hope you don't mind me abusing your issues as a forum!)
