### ISSUE TITLE
The REST path should allow a parameter without the need to suffix it with / (slash)

### ISSUE THREAD

**Issue by slalli** [shabiel/M-Web-Server#58]
Example:
/api/regions/{region}

instead of 

/api/regions/{region}/

**Comment by shabiel** [comment]
@slalli I just downloaded the code and was gonna start debugging it, but I found out that once I removed the `/` from `_weburl` file and tried the call from the web browser without the slash, it just worked, no questions asked. So I am gonna be closing this issue; and the code you wrote you will need to remove all the extra slashes from, which are everywhere...

**Comment by slalli** [comment]
sam, it doesn't work when you have a PARAMETER, like /regions/{region}, that's when it doesn't work...

I already changed and pushed the code for the api/test/error and removed the slash, but the problem is there (not really a problem) when you get a region

**Comment by shabiel** [comment]
Okay. We will try it together tomorrow. Will re-open.

**Comment by shabiel** [comment]
Confirmed fixed with Stef.
