### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jcc5169** [shabiel/M-Web-Server#7]
Would like to use this with WorldVista to integrate with SQL Server SSIS using Web Service Task.  Looking at what will need to be modified.

**Comment by shabiel** [comment]
Who's the producer and who's the consumer??

**Comment by jcc5169** [comment]
I work at Central Regional Hospital for Joe Thurber and we have WorldVista implemented for about 5 years. Producer would be Vista, Consumer would be SQl Server SSIS WebServices Task thru a http connection. Since our implementation is customized, anticipate some incompatibilities. If I run into them, will create a separate branch for mods.

**Comment by jcc5169** [comment]
Was trying to integrate thru C# calling RPC's using Medsphere dll's but SQL Server C# scripting in SSIS is too dedicated to SQL Server.  This looks like a more effective approach for querying VistA for data extraction.

**Comment by jcc5169** [comment]
It is installed and working on port 9080, no problems so far

**Comment by shabiel** [comment]
Okay. I can probably help you more next week.

My email is sam dot habiel at the famous google email service. I have
already written code to help you do what you want to do. If you are curious
to get started, it's in the fileman-web repository on my github.

**Comment by jcc5169** [comment]
Sam,

Thanks for the response.  I may not need help, in the process of looking at the pieces after installing it. Has nice possibilities ..... Thanks for offering, very kind of you.

**Comment by jcc5169** [comment]
Sam,

The description of what I want to add is here. https://en.wikipedia.org/wiki/Web_Services_Description_Language

**Comment by shabiel** [comment]
Holy crap... you want to create a WSDL? Dude, you are on your own. WSDLs
are by and large deprecated... You only want to use them if you need to
ingest .Net or Java data structures.

--Sam

**Comment by jcc5169** [comment]
Sam,


I had already assumed I was "on my own".  :)   WSDL and SOAP are very much alive in the Microsoft world, so I am assuming you are talking about the non-Microsoft world when you say it has been deprecated.  WSDL is just another mime type, and this service will use the building blocks you and others have already put into place. The producer mechanism is what has to be created.  Will let you know how it goes.  It will be an adventure, haven't been working with Mumps that long but I have great respect for the power and flexibility of the language.


Thanks,
Chris Combs
919-602-1952
________________________________
